#!/bin/bash

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
else
    ./install-required
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    ./install-docker
    mvn clean install
    ./build-container
    ./run-container
fi
